export const products = [
  {
    img_url:
      "https://img3.junaroad.com/uiproducts/17927167/pri_175_p-1629181577.jpg",
    product_name: "Classic Black T-Shirt",
    amount: 1900,
    tag: "Regular Fit",
    fabric_style: ["Luxe Soft", "Premium Heavy Fabric"],
    gender: "MEN",
    size: "M",
    brand: "Bewakoof",
    color: "#000",
    sleeve: "Half Sleeve",
    neck: "Round Neck",
    type: "T Shirt",
    ratings: 4.5,
    discount: 10,
  },
  {
    img_url:
      "https://img3.junaroad.com/uiproducts/17927167/pri_175_p-1629181577.jpg",
    product_name: "Casual White Shirt",
    amount: 2900,
    tag: "Few Left",
    fabric_style: ["Premium Heavy Fabric"],
    gender: "MEN",
    size: "L",
    brand: "Difference of Opinion",
    color: "#fff",
    sleeve: "Full Sleeve",
    neck: "Polo",
    type: "Shirt",
    ratings: 4.2,
    discount: 20,
  },
  {
    img_url:
      "https://img3.junaroad.com/uiproducts/17927167/pri_175_p-1629181577.jpg",
    product_name: "Floral Print Dress",
    amount: 3999,
    tag: "Flash Sale",
    fabric_style: ["Organic Cotton", "Feather Light"],
    gender: "WOMEN",
    size: "M",
    brand: "Teeshut",
    color: "#FFC0CB",
    sleeve: "Short T Shirt",
    neck: "Round Neck",
    type: "T Shirt",
    ratings: 4.7,
    discount: 30,
  },
  {
    img_url:
      "https://img3.junaroad.com/uiproducts/17927167/pri_175_p-1629181577.jpg",
    product_name: "Men's Slim Fit Jeans",
    amount: 4999,
    tag: "Buy 1 Get 1 Free",
    fabric_style: ["Premium Heavy Fabric"],
    gender: "MEN",
    size: "XL",
    brand: "Dilinger",
    color: "#008000",
    sleeve: "Drop Shoulder",
    neck: "Henley Neck",
    type: "Jeans",
    ratings: 4.0,
    discount: 40,
  },
  {
    img_url:
      "https://img3.junaroad.com/uiproducts/17927167/pri_175_p-1629181577.jpg",
    product_name: "Women's Hooded Sweatshirt",
    amount: 3499,
    tag: "Few Left",
    fabric_style: ["Luxe Soft", "Premium Heavy Fabric"],
    gender: "WOMEN",
    size: "S",
    brand: "Door 74",
    color: "#e74c3c",
    sleeve: "Full Sleeve",
    neck: "Hooded",
    type: "Hoodies",
    ratings: 4.5,
    discount: 50,
  },
  {
    img_url:
      "https://img3.junaroad.com/uiproducts/17927167/pri_175_p-1629181577.jpg",
    product_name: "Stylish Black Shorts",
    amount: 2599,
    tag: "Regular Fit",
    fabric_style: ["Luxe Soft"],
    gender: "MEN",
    size: "M",
    brand: "The Bargain Street",
    color: "#000",
    sleeve: "3/4 Sleeve",
    neck: "Round Neck",
    type: "Short T Shirt",
    ratings: 3.5,
    discount: 10,
  },
  {
    img_url:
      "https://img3.junaroad.com/uiproducts/17927167/pri_175_p-1629181577.jpg",
    product_name: "Women's High Neck Sweater",
    amount: 4499,
    tag: "Buy 1 Get 1 Free",
    fabric_style: ["Feather Light", "Premium Heavy Fabric"],
    gender: "WOMEN",
    size: "L",
    brand: "Mad Over Print",
    color: "#964B00",
    sleeve: "Full Sleeve",
    neck: "High Neck",
    type: "Hoodies",
    ratings: 4.2,
    discount: 20,
  },
  {
    img_url:
      "https://img3.junaroad.com/uiproducts/17927167/pri_175_p-1629181577.jpg",
    product_name: "Casual Checkered Shirt",
    amount: 3299,
    tag: "Flash Sale",
    fabric_style: ["Organic Cotton", "Premium Heavy Fabric"],
    gender: "MEN",
    size: "S",
    brand: "Weezy",
    color: "#FF0000",
    sleeve: "Half Sleeve",
    neck: "Round Neck",
    type: "Shirt",
    ratings: 3.5,
    discount: 30,
  },
  {
    img_url:
      "https://img3.junaroad.com/uiproducts/17927167/pri_175_p-1629181577.jpg",
    product_name: "Women's Denim Jeans",
    amount: 3999,
    tag: "Few Left",
    fabric_style: ["Premium Heavy Fabric"],
    gender: "WOMEN",
    size: "M",
    brand: "Bewakoof",
    color: "#008000",
    sleeve: "Full Sleeve",
    neck: "Round Neck",
    type: "Jeans",
    ratings: 4.7,
    discount: 40,
  },
  {
    img_url:
      "https://img3.junaroad.com/uiproducts/17927167/pri_175_p-1629181577.jpg",
    product_name: "Casual Striped T-Shirt",
    amount: 1900,
    tag: "Buy 1 Get 1 Free",
    fabric_style: ["Luxe Soft", "Feather Light"],
    gender: "MEN",
    size: "XL",
    brand: "Difference of Opinion",
    color: "#FFFF00",
    sleeve: "3/4 Sleeve",
    neck: "Polo",
    type: "T Shirt",
    ratings: 4.0,
    discount: 50,
  },
];
